#pragma once
// Natives
#include "..\..\inc\natives.h"
#include "..\..\inc\types.h"
#include "..\..\inc\enums.h"
#include "..\..\inc\main.h"
#include "entity.h"
#include "Math.h"

// Scripts
#include "script.h"
#include "keyboard.h"

// Windows Header Files:
#include <windows.h>
#include <Mmsystem.h>
#include <string>
#include <ctime>
#include <vector>
#include <sstream>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <unordered_map>
#include <algorithm>
#include <functional>
#include <Psapi.h>
#include <timeapi.h>
#include <time.h>
#include "../../inc/MinHook/MinHook.h"
#pragma comment(lib, "../../inc/MinHook/libMinHook.x64.lib")

#include "Logger.h";
#include "Stopwatch.h";
#include "Math.h";
#include "world.h";
#include "Weapons.h";
#include "Vehicles.h";
#include "Ped.h";
#include "PedBehavior.h";
#include "Conversation.h";
#include "RobberyInteraction.h";
#include "blips.h";
#include "Prompt.h";
#include "GUIDrawer.h";
#include "AttachedRope.h";
#include "AttachedRopesHanding.h";
#include "BountyDefinitions.h";
#include "ModProgress.h";
#include "MapArea.h";
#include "MapAreasManager.h";
#include "BountyMissionData.h";
#include "BaseMissionExecutor.h";
#include "EliasTraditionExecutor.h";
#include "TreasuryPeteExecutor.h";
#include "ChesterBurnettExecutor.h";
#include "HankEnepayExecutor.h";
#include "NateNashobaExecutor.h";
#include "CharlesMoonExecutor.h";
#include "GushkalaInataExecutor.h";
#include "TurkishRunnerExecutor.h";
#include "JaneBullionExecutor.h";
#include "RobertCorbucciExecutor.h";
#include "ClintonvonHagenExecutor.h";
#include "JuanCortezExecutor.h";
#include "RichardMooreExecutor.h";
#include "ArchStantonExecutor.h";
#include "JacobSeedExecutor.h";
#include "AndrewClarkExecutor.h";
#include "TucoVillaExecutor.h";
#include "JesseHillExecutor.h";
#include "BillyWilsonExecutor.h";
#include "JoseChavezExecutor.h";
#include "PeteEatonExecutor.h";
#include "MarquisRussellExecutor.h";
#include "JohnBullExecutor.h";
#include "WallaceKnoxExecutor.h";
#include "HarperConnorExecutor.h";
#include "EmmettDavisExecutor.h";
#include "MikeSandersExecutor.h";
#include "ChrisJaniceExecutor.h";
#include "CarlMartinExecutor.h";
#include "JustusBarnesExecutor.h";
#include "BufordDukeExecutor.h";
#include "CullenBakerExecutor.h";
#include "WilliamRogersExecutor.h";
#include "BobLaneExecutor.h";
#include "GeorgeCoenExecutor.h";
#include "BuckHicoxExecutor.h";
#include "JohnEastwoodExecutor.h";
#include "PanchoDanielExecutor.h";
#include "QuentinChigurhExecutor.h";
#include "BountyMissionsFactory.h";
#include "Autosave.h";
#include "BountiesManager.h";
#include "BountiesMenu.h";
#include "UI.h";